// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raythos;

#nullable disable

namespace Raythos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Raythos.Models.Address", b =>
                {
                    b.Property<long>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AddressID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("AddressID");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Raythos.Models.Aircraft", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("FuelCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<DateTime>("ManufacturedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxSpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Raythos.Models.AircraftCustomization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AircraftId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("AircraftCustomizations");
                });

            modelBuilder.Entity("Raythos.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "93",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "358",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "355",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "213",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "1",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "376",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "244",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "1",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "1",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "54",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "374",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "297",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 13L,
                            Code = "61",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 14L,
                            Code = "43",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 15L,
                            Code = "994",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 16L,
                            Code = "1",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 17L,
                            Code = "973",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 18L,
                            Code = "880",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 19L,
                            Code = "1",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 20L,
                            Code = "375",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 21L,
                            Code = "32",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 22L,
                            Code = "501",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 23L,
                            Code = "229",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 24L,
                            Code = "1",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 25L,
                            Code = "975",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 26L,
                            Code = "591",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 27L,
                            Code = "599",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 28L,
                            Code = "387",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 29L,
                            Code = "267",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 30L,
                            Code = "55",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 31L,
                            Code = "246",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 32L,
                            Code = "1",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 33L,
                            Code = "673",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 34L,
                            Code = "359",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 35L,
                            Code = "226",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 36L,
                            Code = "257",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 37L,
                            Code = "238",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 38L,
                            Code = "855",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 39L,
                            Code = "237",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 40L,
                            Code = "1",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41L,
                            Code = "0",
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 42L,
                            Code = "1",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 43L,
                            Code = "236",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 44L,
                            Code = "235",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45L,
                            Code = "56",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 46L,
                            Code = "86",
                            Name = "China"
                        },
                        new
                        {
                            Id = 47L,
                            Code = "61",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 48L,
                            Code = "61",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 49L,
                            Code = "57",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 50L,
                            Code = "269",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 51L,
                            Code = "242",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 52L,
                            Code = "243",
                            Name = "Congo (DRC)"
                        },
                        new
                        {
                            Id = 53L,
                            Code = "682",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 54L,
                            Code = "506",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 55L,
                            Code = "225",
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 56L,
                            Code = "385",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 57L,
                            Code = "53",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 58L,
                            Code = "599",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 59L,
                            Code = "357",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 60L,
                            Code = "420",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 61L,
                            Code = "45",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 62L,
                            Code = "253",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 63L,
                            Code = "1",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 64L,
                            Code = "1",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 65L,
                            Code = "593",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 66L,
                            Code = "20",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 67L,
                            Code = "503",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 68L,
                            Code = "240",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 69L,
                            Code = "291",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 70L,
                            Code = "372",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 71L,
                            Code = "251",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 72L,
                            Code = "0",
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 73L,
                            Code = "500",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = 74L,
                            Code = "298",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 75L,
                            Code = "679",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 76L,
                            Code = "358",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 77L,
                            Code = "33",
                            Name = "France"
                        },
                        new
                        {
                            Id = 78L,
                            Code = "594",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 79L,
                            Code = "689",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 80L,
                            Code = "241",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 81L,
                            Code = "220",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 82L,
                            Code = "995",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 83L,
                            Code = "49",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 84L,
                            Code = "233",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 85L,
                            Code = "350",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 86L,
                            Code = "30",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 87L,
                            Code = "299",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 88L,
                            Code = "1",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 89L,
                            Code = "590",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 90L,
                            Code = "1",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 91L,
                            Code = "502",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 92L,
                            Code = "44",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 93L,
                            Code = "224",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 94L,
                            Code = "245",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 95L,
                            Code = "592",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 96L,
                            Code = "509",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 97L,
                            Code = "504",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 98L,
                            Code = "852",
                            Name = "Hong Kong SAR"
                        },
                        new
                        {
                            Id = 99L,
                            Code = "36",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 100L,
                            Code = "354",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 101L,
                            Code = "91",
                            Name = "India"
                        },
                        new
                        {
                            Id = 102L,
                            Code = "62",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 103L,
                            Code = "98",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 104L,
                            Code = "964",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 105L,
                            Code = "353",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 106L,
                            Code = "44",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 107L,
                            Code = "972",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 108L,
                            Code = "39",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 109L,
                            Code = "1",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 110L,
                            Code = "81",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 111L,
                            Code = "44",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 112L,
                            Code = "962",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 113L,
                            Code = "7",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 114L,
                            Code = "254",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 115L,
                            Code = "686",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 116L,
                            Code = "82",
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 117L,
                            Code = "383",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 118L,
                            Code = "965",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 119L,
                            Code = "996",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 120L,
                            Code = "856",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 121L,
                            Code = "0",
                            Name = "Latin America"
                        },
                        new
                        {
                            Id = 122L,
                            Code = "371",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 123L,
                            Code = "961",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 124L,
                            Code = "266",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 125L,
                            Code = "231",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 126L,
                            Code = "218",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 127L,
                            Code = "423",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 128L,
                            Code = "370",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 129L,
                            Code = "352",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 130L,
                            Code = "853",
                            Name = "Macao SAR"
                        },
                        new
                        {
                            Id = 131L,
                            Code = "389",
                            Name = "Macedonia, FYRO"
                        },
                        new
                        {
                            Id = 132L,
                            Code = "261",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 133L,
                            Code = "265",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 134L,
                            Code = "60",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 135L,
                            Code = "960",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 136L,
                            Code = "223",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 137L,
                            Code = "356",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 138L,
                            Code = "692",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 139L,
                            Code = "596",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 140L,
                            Code = "222",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 141L,
                            Code = "230",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 142L,
                            Code = "262",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 143L,
                            Code = "52",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 144L,
                            Code = "691",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 145L,
                            Code = "373",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 146L,
                            Code = "377",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 147L,
                            Code = "976",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 148L,
                            Code = "382",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 149L,
                            Code = "1",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 150L,
                            Code = "212",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 151L,
                            Code = "258",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 152L,
                            Code = "95",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 153L,
                            Code = "264",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 154L,
                            Code = "674",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 155L,
                            Code = "977",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 156L,
                            Code = "31",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 157L,
                            Code = "687",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 158L,
                            Code = "64",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 159L,
                            Code = "505",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 160L,
                            Code = "227",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 161L,
                            Code = "234",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 162L,
                            Code = "683",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 163L,
                            Code = "672",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 164L,
                            Code = "850",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 165L,
                            Code = "1",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 166L,
                            Code = "47",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 167L,
                            Code = "968",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 168L,
                            Code = "92",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 169L,
                            Code = "680",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 170L,
                            Code = "970",
                            Name = "Palestinian Authority"
                        },
                        new
                        {
                            Id = 171L,
                            Code = "507",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 172L,
                            Code = "675",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 173L,
                            Code = "595",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 174L,
                            Code = "51",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 175L,
                            Code = "63",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 176L,
                            Code = "0",
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 177L,
                            Code = "48",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 178L,
                            Code = "351",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 179L,
                            Code = "1",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 180L,
                            Code = "974",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 181L,
                            Code = "262",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 182L,
                            Code = "40",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 183L,
                            Code = "7",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 184L,
                            Code = "250",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 185L,
                            Code = "590",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 186L,
                            Code = "1",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 187L,
                            Code = "1",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 188L,
                            Code = "590",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 189L,
                            Code = "508",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 190L,
                            Code = "1",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 191L,
                            Code = "685",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 192L,
                            Code = "378",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 193L,
                            Code = "239",
                            Name = "São Tomé and Príncipe"
                        },
                        new
                        {
                            Id = 194L,
                            Code = "966",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 195L,
                            Code = "221",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 196L,
                            Code = "381",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 197L,
                            Code = "248",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 198L,
                            Code = "232",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 199L,
                            Code = "65",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 200L,
                            Code = "1",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 201L,
                            Code = "421",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 202L,
                            Code = "386",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 203L,
                            Code = "677",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 204L,
                            Code = "252",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 205L,
                            Code = "27",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 206L,
                            Code = "211",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 207L,
                            Code = "34",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 208L,
                            Code = "94",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 209L,
                            Code = "290",
                            Name = "St Helena, Ascension, Tristan da Cunha"
                        },
                        new
                        {
                            Id = 210L,
                            Code = "249",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 211L,
                            Code = "597",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 212L,
                            Code = "47",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 213L,
                            Code = "268",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 214L,
                            Code = "46",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 215L,
                            Code = "41",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 216L,
                            Code = "963",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 217L,
                            Code = "886",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 218L,
                            Code = "992",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 219L,
                            Code = "255",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 220L,
                            Code = "66",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 221L,
                            Code = "670",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 222L,
                            Code = "228",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 223L,
                            Code = "690",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 224L,
                            Code = "676",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 225L,
                            Code = "1",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 226L,
                            Code = "216",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 227L,
                            Code = "90",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 228L,
                            Code = "993",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 229L,
                            Code = "1",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 230L,
                            Code = "688",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 231L,
                            Code = "0",
                            Name = "U.S. Outlying Islands"
                        },
                        new
                        {
                            Id = 232L,
                            Code = "1",
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Id = 233L,
                            Code = "256",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 234L,
                            Code = "380",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 235L,
                            Code = "971",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 236L,
                            Code = "44",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 237L,
                            Code = "1",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 238L,
                            Code = "598",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 239L,
                            Code = "998",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 240L,
                            Code = "678",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 241L,
                            Code = "39",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 242L,
                            Code = "58",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 243L,
                            Code = "84",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 244L,
                            Code = "681",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 245L,
                            Code = "0",
                            Name = "World"
                        },
                        new
                        {
                            Id = 246L,
                            Code = "967",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 247L,
                            Code = "260",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 248L,
                            Code = "263",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Raythos.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AircraftCustomizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("AircraftId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("AircraftCustomizationId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Raythos.Models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Raythos.Models.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Raythos.Models.TeamMember", b =>
                {
                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TeamId", "UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Raythos.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContactNo = "1234567890",
                            CreatedAt = new DateTime(2023, 12, 27, 2, 3, 47, 519, DateTimeKind.Local).AddTicks(492),
                            Email = "admin@system.com",
                            FName = "Admin",
                            IsAdmin = true,
                            LName = "System",
                            Password = "$2a$11$v86XbOw4xPESlHagig1brOFQwIgujLJWKQJ22OUcKTnFvJ5BFCnfC",
                            UpdatedAt = new DateTime(2023, 12, 27, 2, 3, 47, 519, DateTimeKind.Local).AddTicks(510)
                        });
                });

            modelBuilder.Entity("Raythos.Models.Address", b =>
                {
                    b.HasOne("Raythos.Models.Country", "Country")
                        .WithMany("Addresses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raythos.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Raythos.Models.Aircraft", b =>
                {
                    b.HasOne("Raythos.Models.Team", "Team")
                        .WithOne("Aircraft")
                        .HasForeignKey("Raythos.Models.Aircraft", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Raythos.Models.AircraftCustomization", b =>
                {
                    b.HasOne("Raythos.Models.Aircraft", "Aircraft")
                        .WithMany("AircraftCustomizations")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("Raythos.Models.Order", b =>
                {
                    b.HasOne("Raythos.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Raythos.Models.AircraftCustomization", null)
                        .WithMany("Orders")
                        .HasForeignKey("AircraftCustomizationId");

                    b.HasOne("Raythos.Models.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raythos.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Address");

                    b.Navigation("Aircraft");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Raythos.Models.Payment", b =>
                {
                    b.HasOne("Raythos.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Raythos.Models.TeamMember", b =>
                {
                    b.HasOne("Raythos.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Raythos.Models.Aircraft", b =>
                {
                    b.Navigation("AircraftCustomizations");
                });

            modelBuilder.Entity("Raythos.Models.AircraftCustomization", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Raythos.Models.Country", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Raythos.Models.Team", b =>
                {
                    b.Navigation("Aircraft")
                        .IsRequired();

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Raythos.Models.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
